spring:
   r2dbc:
      url: r2dbc:postgresql://postgres-db-postgresql.polarbookshop-production.svc.cluster.local:5432/polardb_order
      username: postgres
   config:
      import: configtree:/workspace/secrets/*/  
polar:
   catalog-service-uri: http://catalog-service:80

                  